### ISSUE TITLE
Document the new basic ECIES encryptor

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-crypto#149]
We have introduced a more standardized implementation of ECIES encryptor. We also need to document it.

**Comment by petrdvorak** [comment]
I prepared an ECIES documentation here:

https://github.com/lime-company/powerauth-crypto/wiki/End-To-End-Encryption

@hvge Is there still something missing?

**Comment by hvge** [comment]
In **Encryption, step 3** (or in **Decryption, step 2**), the optional "info" parameter is actually not optional (it's optional, but only from that KDF function's perspective). Our scheme requires here to use `KEY_EPH_PUB` as input to info parameter. Our current implementation is using `KEY_EPH_PUB` in form of exact key bytes as received with the encrypted payload (if you look at it from server's perspective). This should be also noted in the documentation. Just for your info, I'm keeping a short note about the protocol also in our [C++ code documentation](https://github.com/lime-company/powerauth-mobile-sdk/blob/develop/include/PowerAuth/ECIES.h). 

In **Encryption, step 4**, you're using "sharedInfo" parameter, but this is typically called as "sharedInfo2"  in research papers (or S2, SH2, param2, etc...). This is a minor issue, but may confuse readers already familiar with ECIES. I think we should keep this naming, even if our implementation has S1 as not configurable. Now it looks like that you're providing S1 but it's actually S2

**Comment by petrdvorak** [comment]
I see - I fixed the issue from comments, now the docs should be OK.
